apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: abdullahi-gitops
servers: 1 # Master Nodes
agents: 2 # Worker Nodes
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*