apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app1
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/abdullahishs/k3d-gitops/  
    targetRevision: testing-branch
    path: argocd/apps/demo-app1/demo-of-demoapp1/

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
