name: Create K3d Cluster

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'cluster/**'

jobs:
  build-k3d-cluster:
    name: Create the k3d Cluster
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install K3d
      shell: bash
      run: |
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        k3d --version

    - name: Create Cluster Using Config
      shell: bash
      run: |
        k3d cluster create -c cluster/abdullahi-gitops.yaml
        kubectl --version

    - name: Add Argo Helm repo
      run: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update

    - name: Create ArgoCD namespace
      run: |
        kubectl create namespace argocd || true

    - name: Install ArgoCD via Helm
      run: |
        helm upgrade --install argocd argo/argo-cd -n argocd -f argocd/values.yaml

    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f argocd/apps/demo-app1/app.yaml